In [1]:
import numpy as np
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [3]:
np.zeros(3)

array([0., 0., 0.])

In [4]:
np.ones(3)

array([1., 1., 1.])

In [5]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [6]:
np.linspace(0,10,4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [7]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [8]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [9]:
np.random.rand(2)

array([0.79876767, 0.96903963])

In [10]:
np.random.rand(5,5)

array([[0.23446768, 0.8107017 , 0.19448734, 0.91642202, 0.47756796],
       [0.36721722, 0.34011046, 0.86067611, 0.91351093, 0.49750418],
       [0.00567033, 0.32859401, 0.9117354 , 0.12903327, 0.64556708],
       [0.31610473, 0.75711466, 0.39513624, 0.99076192, 0.04620719],
       [0.06891833, 0.87813521, 0.53592818, 0.92879147, 0.07883514]])

In [13]:
np.random.randint(1,100)

32

In [12]:
np.random.randint(1,100,10)   #10 different random numbers 1-100

array([55, 45,  2, 36, 55, 39, 33, 34, 52, 75])

In [14]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [15]:
np.arange(1,101).reshape(10,10)/100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

# Elements wise arithmetic operation


In [28]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
print(x)
y

[[1 2]
 [3 4]]


array([[5, 6],
       [7, 8]])

In [23]:
print(np.add(x,y))

[[ 6  8]
 [10 12]]


In [24]:
print(np.subtract(x,y))

[[-4 -4]
 [-4 -4]]


In [25]:
print(np.multiply(x,y))

[[ 5 12]
 [21 32]]


In [26]:
print(np.divide(x,y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [27]:
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]
