In [6]:
import numpy as np
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [8]:
 #[startindex: endindex : stepsize]
a[0,1:6:2]

array([2, 4, 6])

In [9]:
# get a specific column
a[:, 2]

array([ 3, 10])

In [10]:
#get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [11]:
#get a specific element [r,c]
a[1, 5]

13

In [12]:
#change value in array
a[1,5] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [13]:
a[:,2]= [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [14]:
#3d example
b= np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [18]:
#get specific element (work outside in)
b[0,1,1]

4

In [22]:
#replace
b[:,1,:] =[[9,9],[8,8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


In [31]:
c = np.arange(40).reshape((8,5))

In [27]:
c

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]])