In [1]:
import numpy as np
#Numpy data types
#bool = true, false
#int = integer #
#float = 1.5
#complex = 1 +3j
#numpy array can only have one data type


In [2]:
A = [1,2,3,4,5]
B = [1.5,2.5,3.5]
C = [1, 1.5, 2 , 2.5 , 2.3]

In [3]:
print(type(C))

<class 'list'>


In [14]:
ArrayA = np.array(A, dtype=np.int32) #32 is byte size
ArrayB = np.array(B, dtype=np.float32)
ArrayC = np.array(C)


In [16]:
print(A)
print(ArrayA)
print(ArrayB)
print(ArrayC)

[1, 2, 3, 4, 5]
[1 2 3 4 5]
[1.5 2.5 3.5]
['1' '1.5' '2' '2.5' 'string']


['1' '1.5' '2' '2.5' 'string']


In [17]:
D = [[1,2], [3,4], [5,6],[7,8]]
ArrayD = np.array(D, dtype=np.int32)
print(ArrayD)
print(ArrayD.shape)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
(4, 2)
