In [2]:
import numpy as np
array1 = np.empty((12,5))

In [13]:
for x in range(12):
    array1[x] = x

In [30]:
array1

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.,  7.],
       [ 8.,  8.,  8.,  8.,  8.],
       [ 9.,  9.,  9.,  9.,  9.],
       [10., 10., 10., 10., 10.],
       [11., 11., 11., 11., 11.]])

In [14]:
array1[[2,4,6,8]]

array([[2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8.]])

In [19]:
array1[[-2,-4]]

array([[10., 10., 10., 10., 10.],
       [ 8.,  8.,  8.,  8.,  8.]])

In [20]:
#another array
array2 = np.arange(40).reshape((8,5))

In [21]:
array2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]])

In [31]:
#get specific numbers  [row ,row], [col,col]
array2[[6,6],[1,2]] 

array([31, 32])