In [4]:
import numpy as np
#All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [7]:
#All 1s matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [13]:
#Any other number
np.full((2,2),23)

array([[23, 23],
       [23, 23]])

In [14]:
#any other number (full_like)
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
#np.full(a.shape,4) same as below
np.full_like(a,4)


array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [21]:
#random decimal numbers
np.random.random_sample(a.shape)

array([[0.04718252, 0.39394759, 0.62984283, 0.83228361, 0.30328167,
        0.35328027, 0.08980775],
       [0.36321728, 0.15224809, 0.7233949 , 0.43952767, 0.60486236,
        0.75860729, 0.66723314]])

In [28]:
np.random.rand(4,2)

array([[0.7738571 , 0.80733334],
       [0.61565635, 0.65762531],
       [0.29031119, 0.22870587],
       [0.72992527, 0.27036308]])

In [29]:
#random integer values
np.random.randint(-4,1,size=(3,3))

array([[-2, -2,  0],
       [-2, -4, -2],
       [-2, -1, -1]])

In [30]:
#The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [33]:
#repeat an array
arr = np.array([1,2,3])
r1= np.repeat(arr,3)
print(r1)

[1 1 1 2 2 2 3 3 3]


In [34]:
arr = np.array([[1,2,3]])
r1= np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:4,1:4] = z
print(output)


#### be careful when copying arrays!!


In [41]:
a = np.array([1,2,3])
b= a
b[0]=100
print(a)

[100   2   3]


In [42]:
a = np.array([1,2,3])
b= a.copy()
b[0]=100
print(a)

[1 2 3]
