In [4]:
import numpy as np
#transposing array in 2D array
#swapaxes can only rearranged 2D
#while transpose can rearrange all dimensions

array1 = np.arange(1,11).reshape(5,2)
array1

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [6]:
np.transpose(array1)

array([[ 1,  3,  5,  7,  9],
       [ 2,  4,  6,  8, 10]])

In [10]:
array1.shape

(5, 2)

In [11]:
np.transpose(array1).shape

(2, 5)

In [12]:
#transposing array in 3D array

In [13]:
a = np.arange (1,25).reshape(2,3,4)   #(2 is array count, 3 is row, 4 is col)
a

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [14]:
np.transpose(a)

array([[[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]],

       [[ 4, 16],
        [ 8, 20],
        [12, 24]]])

In [15]:
np.transpose(a).shape   ()

(4, 3, 2)

In [16]:
#transpose
np.transpose(array1, axes=(1,0))


array([[ 1,  3,  5,  7,  9],
       [ 2,  4,  6,  8, 10]])

In [17]:
np.transpose(array1, axes=(0,1))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [20]:
a = np.arange (1,25).reshape(2,3,4)   #(2 is array count, 3 is row, 4 is col)
a

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [19]:
np.transpose(a,(1,2,0))    #(1=3, 2=4 ,0=2) from above which means it will  
# be 3 2D arrays ,4 rows and 2 columns

array([[[ 1, 13],
        [ 2, 14],
        [ 3, 15],
        [ 4, 16]],

       [[ 5, 17],
        [ 6, 18],
        [ 7, 19],
        [ 8, 20]],

       [[ 9, 21],
        [10, 22],
        [11, 23],
        [12, 24]]])

In [21]:
a.T

array([[[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]],

       [[ 4, 16],
        [ 8, 20],
        [12, 24]]])

In [26]:
#swapaxes
np.swapaxes(a,1,0)

array([[[ 1,  2,  3,  4],
        [13, 14, 15, 16]],

       [[ 5,  6,  7,  8],
        [17, 18, 19, 20]],

       [[ 9, 10, 11, 12],
        [21, 22, 23, 24]]])

In [25]:
a.shape
#(2=row, 3 = counts array , 4= column)

(2, 3, 4)

In [28]:
np.swapaxes(a,1,2)

array([[[ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11],
        [ 4,  8, 12]],

       [[13, 17, 21],
        [14, 18, 22],
        [15, 19, 23],
        [16, 20, 24]]])

In [29]:
np.swapaxes(a,1,2).shape #before the shape is 2,3,4 now its 2,4,3

(2, 4, 3)

In [33]:
a.swapaxes(1,2) # this will give the same output

array([[[ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11],
        [ 4,  8, 12]],

       [[13, 17, 21],
        [14, 18, 22],
        [15, 19, 23],
        [16, 20, 24]]])